from django.contrib import admin


# Register your models here.
from .models import (AboutIcons, SearchBox, HomeIcons, SlaysiteIcons, News_article, Web, KoinoniaVideo, Koinonia, KoinoniaVidAMO, 
KoinoniaAMO, Koinonia_Others, Hillsong, Amazon, Apps, Arts, AudioBook, AutoMobiles, Banking, Bcosmetics, Birthday, Books, Browsers,
Cartoons, Cfood, Disney, Education, Entertainment, Fashion, Gaming, Gdp, Google, Gdesign, HealthCare, Images, Jobs, Microsoft, Movies, 
Music, News, OnlineDating, OnlinePayment, Opera, Pdfs, Programming, Shopping, Social, Sports, Travel, Tv_Shows, Videos,
Weather, WebHosting, Wikipedia, WWE, Covid_19, AboutIcons, TourAll, TourMovies, TourMusics, TourSports, TourNews, TourGames)

admin.site.register(SearchBox)
admin.site.register(HomeIcons)
admin.site.register(SlaysiteIcons)
admin.site.register(News_article)
admin.site.register(Web)
admin.site.register(KoinoniaVideo)
admin.site.register(Koinonia)
admin.site.register(KoinoniaVidAMO)
admin.site.register(KoinoniaAMO)
admin.site.register(Koinonia_Others)
admin.site.register(Hillsong)
admin.site.register(Amazon)
admin.site.register(Apps)
admin.site.register(Arts)
admin.site.register(AudioBook)
admin.site.register(AutoMobiles)
admin.site.register(Banking)
admin.site.register(Bcosmetics)
admin.site.register(Birthday)
admin.site.register(Books)
admin.site.register(Browsers)
admin.site.register(Cartoons)
admin.site.register(Cfood)
admin.site.register(Disney)
admin.site.register(Education)
admin.site.register(Entertainment)
admin.site.register(Fashion)
admin.site.register(Gaming)
admin.site.register(Gdp)
admin.site.register(Google)
admin.site.register(Gdesign)
admin.site.register(HealthCare)
admin.site.register(Images)
admin.site.register(Jobs)
admin.site.register(Microsoft)
admin.site.register(Movies)
admin.site.register(Music)
admin.site.register(News)
admin.site.register(OnlineDating)
admin.site.register(OnlinePayment)
admin.site.register(Opera)
admin.site.register(Pdfs)
admin.site.register(Programming)
admin.site.register(Shopping)
admin.site.register(Social)
admin.site.register(Sports)
admin.site.register(Travel)
admin.site.register(Tv_Shows)
admin.site.register(Videos)
admin.site.register(Weather)
admin.site.register(WebHosting)
admin.site.register(Wikipedia)
admin.site.register(WWE)
admin.site.register(Covid_19)
admin.site.register(AboutIcons)
admin.site.register(TourAll)
admin.site.register(TourMovies)
admin.site.register(TourMusics)
admin.site.register(TourSports)
admin.site.register(TourNews)
admin.site.register(TourGames)