# Generated by Django 3.1.1 on 2022-01-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchbox_title', models.CharField(blank=True, max_length=1000)),
                ('searchbox_url', models.URLField()),
            ],
        ),
    ]
