# Generated by Django 3.1.1 on 2022-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeicon_title', models.CharField(max_length=50)),
                ('homeicon_url', models.URLField()),
                ('homeicon_file', models.ImageField(default='default.png', upload_to='home_icons')),
            ],
        ),
    ]
