# Generated by Django 3.1.1 on 2040-01-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0002_homeicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaysiteIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaysiteicon_file', models.ImageField(upload_to='slaysite_icons')),
            ],
        ),
    ]
