# Generated by Django 3.1.1 on 2022-01-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0004_slaysiteicons_slaysiteicon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_article_head', models.CharField(blank=True, max_length=50)),
                ('news_article_title', models.CharField(max_length=100)),
                ('news_article_url', models.URLField()),
                ('news_article_file', models.ImageField(blank=True, default='newsdefault.png', upload_to='News_article')),
            ],
        ),
    ]
