# Generated by Django 3.1.1 on 2022-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0006_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='web_file',
            field=models.ImageField(blank=True, default='default.png', upload_to='web_icons'),
        ),
    ]
