# Generated by Django 3.1.1 on 2022-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0007_auto_20220104_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_title', models.CharField(max_length=100)),
                ('amazon_url', models.URLField()),
                ('amazon_file', models.ImageField(blank=True, default='default.png', upload_to='amazon_icons')),
            ],
        ),
    ]
