# Generated by Django 3.1.1 on 2022-01-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0008_amazon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aps_title', models.CharField(max_length=100)),
                ('aps_url', models.URLField()),
                ('aps_file', models.ImageField(blank=True, default='default.png', upload_to='apps_icons')),
            ],
        ),
    ]
