# Generated by Django 3.1.1 on 2022-01-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0009_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=100)),
                ('art_url', models.URLField()),
                ('art_file', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
