# Generated by Django 3.1.1 on 2022-01-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0010_arts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='art_file',
            field=models.ImageField(blank=True, default='default.png', upload_to='arts_icons'),
        ),
    ]
