# Generated by Django 3.1.1 on 2022-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0011_auto_20220105_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook_title', models.CharField(max_length=100)),
                ('audiobook_url', models.URLField()),
                ('audiobook_file', models.ImageField(blank=True, default='default.png', upload_to='audiobook_icons')),
            ],
        ),
    ]
