# Generated by Django 3.1.1 on 2040-01-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0013_automobiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_title', models.CharField(max_length=100)),
                ('banking_url', models.URLField()),
                ('banking_file', models.ImageField(blank=True, default='default.png', upload_to='banking_icons')),
            ],
        ),
    ]
