# Generated by Django 3.1.1 on 2040-01-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0014_banking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcosmetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcosmetics_title', models.CharField(max_length=100)),
                ('bcosmetics_url', models.URLField()),
                ('bcosmetics_file', models.ImageField(blank=True, default='default.png', upload_to='bcosmetics_icons')),
            ],
        ),
    ]
