# Generated by Django 3.1.1 on 2040-01-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0015_bcosmetics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_title', models.CharField(max_length=100)),
                ('birthday_url', models.URLField()),
                ('birthday_file', models.ImageField(blank=True, default='default.png', upload_to='birthday_icons')),
            ],
        ),
    ]
