# Generated by Django 3.1.1 on 2040-01-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0018_browsers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoons_title', models.CharField(max_length=100)),
                ('cartoons_url', models.URLField()),
                ('cartoons_file', models.ImageField(blank=True, default='default.png', upload_to='cartoons_icons')),
            ],
        ),
    ]
