# Generated by Django 3.1.1 on 2040-01-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0020_cfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disney_title', models.CharField(max_length=100)),
                ('disney_url', models.URLField()),
                ('disney_file', models.ImageField(blank=True, default='default.png', upload_to='disney_icons')),
            ],
        ),
    ]
