# Generated by Django 3.1.1 on 2040-01-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0022_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment_title', models.CharField(max_length=100)),
                ('entertainment_url', models.URLField()),
                ('entertainment_file', models.ImageField(blank=True, default='default.png', upload_to='entertainment_icons')),
            ],
        ),
    ]
