# Generated by Django 3.1.1 on 2040-01-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0023_entertainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_title', models.CharField(max_length=100)),
                ('fashion_url', models.URLField()),
                ('fashion_file', models.ImageField(blank=True, default='default.png', upload_to='fashion_icons')),
            ],
        ),
    ]
