# Generated by Django 3.1.1 on 2040-01-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0025_gaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdp_title', models.CharField(max_length=100)),
                ('gdp_url', models.URLField()),
                ('gdp_file', models.ImageField(blank=True, default='default.png', upload_to='gdp_icons')),
            ],
        ),
    ]
