# Generated by Django 3.1.1 on 2040-01-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0026_gdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_title', models.CharField(max_length=100)),
                ('google_url', models.URLField()),
                ('google_file', models.ImageField(blank=True, default='default.png', upload_to='google_icons')),
            ],
        ),
    ]
