# Generated by Django 3.1.1 on 2040-01-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0027_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdesign_title', models.CharField(max_length=100)),
                ('gdesign_url', models.URLField()),
                ('gdesign_file', models.ImageField(blank=True, default='default.png', upload_to='gdesign_icons')),
            ],
        ),
    ]
