# Generated by Django 3.1.1 on 2040-01-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0029_healthcare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_title', models.CharField(max_length=100)),
                ('images_url', models.URLField()),
                ('images_file', models.ImageField(blank=True, default='default.png', upload_to='images_icons')),
            ],
        ),
    ]
