# Generated by Django 3.1.1 on 2040-01-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0030_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_title', models.CharField(max_length=100)),
                ('jobs_url', models.URLField()),
                ('jobs_file', models.ImageField(blank=True, default='default.png', upload_to='jobs_icons')),
            ],
        ),
    ]
