# Generated by Django 3.1.1 on 2040-01-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0031_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microsoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_title', models.CharField(max_length=100)),
                ('microsoft_url', models.URLField()),
                ('microsoft_file', models.ImageField(blank=True, default='default.png', upload_to='microsoft_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_title', models.CharField(max_length=100)),
                ('movies_url', models.URLField()),
                ('movies_file', models.ImageField(blank=True, default='default.png', upload_to='movies_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=100)),
                ('music_url', models.URLField()),
                ('music_file', models.ImageField(blank=True, default='default.png', upload_to='music_icons')),
            ],
        ),
    ]
