# Generated by Django 3.1.1 on 2022-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0034_onlinedating'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_payment_title', models.CharField(max_length=100)),
                ('online_payment_url', models.URLField()),
                ('online_payment_file', models.ImageField(blank=True, default='default.png', upload_to='online_payment_icons')),
            ],
        ),
    ]
