# Generated by Django 3.1.1 on 2022-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0035_onlinepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opera_title', models.CharField(max_length=100)),
                ('opera_url', models.URLField()),
                ('opera_file', models.ImageField(blank=True, default='default.png', upload_to='opera_icons')),
            ],
        ),
    ]
