# Generated by Django 3.1.1 on 2022-01-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0036_opera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfs_title', models.CharField(max_length=100)),
                ('pdfs_url', models.URLField()),
                ('pdfs_file', models.ImageField(blank=True, default='default.png', upload_to='pdfs_icons')),
            ],
        ),
    ]
