# Generated by Django 3.1.1 on 2022-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0037_pdfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(max_length=100)),
                ('program_url', models.URLField()),
                ('program_file', models.ImageField(blank=True, default='default.png', upload_to='programming_icons')),
            ],
        ),
    ]
