# Generated by Django 3.1.1 on 2022-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0038_programming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_title', models.CharField(max_length=100)),
                ('shopping_url', models.URLField()),
                ('shopping_file', models.ImageField(blank=True, default='default.png', upload_to='shopping_icons')),
            ],
        ),
    ]
