# Generated by Django 3.1.1 on 2022-01-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0040_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_title', models.CharField(max_length=100)),
                ('sports_url', models.URLField()),
                ('sports_file', models.ImageField(blank=True, default='default.png', upload_to='sports_icons')),
            ],
        ),
    ]
