# Generated by Django 3.1.1 on 2022-01-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0041_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_title', models.CharField(max_length=100)),
                ('travel_url', models.URLField()),
                ('travel_file', models.ImageField(blank=True, default='default.png', upload_to='travel_icons')),
            ],
        ),
    ]
