# Generated by Django 3.1.1 on 2022-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0042_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvshows_title', models.CharField(max_length=100)),
                ('tvshows_url', models.URLField()),
                ('tvshows_file', models.ImageField(blank=True, default='default.png', upload_to='tvshows_icons')),
            ],
        ),
    ]
