# Generated by Django 3.1.1 on 2022-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0045_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhost_title', models.CharField(max_length=100)),
                ('webhost_url', models.URLField()),
                ('webhost_file', models.ImageField(blank=True, default='default.png', upload_to='webhost_icons')),
            ],
        ),
    ]
