# Generated by Django 3.1.1 on 2022-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0046_webhosting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikipedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikipedia_title', models.CharField(max_length=100)),
                ('wikipedia_url', models.URLField()),
                ('wikipedia_file', models.ImageField(blank=True, default='default.png', upload_to='wikipedia_icons')),
            ],
        ),
    ]
