# Generated by Django 3.1.1 on 2022-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0047_wikipedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='WWE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwe_title', models.CharField(max_length=100)),
                ('wwe_url', models.URLField()),
                ('wwe_file', models.ImageField(blank=True, default='default.png', upload_to='wwe_icons')),
            ],
        ),
    ]
