# Generated by Django 3.1.1 on 2022-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0048_wwe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid_19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid19_title', models.CharField(max_length=100)),
                ('covid19_url', models.URLField()),
                ('covid19_file', models.ImageField(blank=True, default='default.png', upload_to='covid19_icons')),
            ],
        ),
    ]
