# Generated by Django 3.1.1 on 2022-01-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0049_covid_19'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abouticon_file', models.ImageField(upload_to='aboutpage_icons')),
                ('abouticon_title', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
