# Generated by Django 3.1.1 on 2022-01-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0051_hillsong_koinonia_koinonia_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourall_title', models.CharField(max_length=100)),
                ('tourall_video', models.FileField(default='', upload_to='Tourall/%y')),
                ('tourall_file', models.ImageField(blank=True, default='default.png', upload_to='Tourall')),
            ],
        ),
    ]
