# Generated by Django 3.1.1 on 2022-01-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0052_tourall'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourgames_title', models.CharField(max_length=100)),
                ('tourgames_video', models.FileField(default='', upload_to='Tourgames/%y')),
                ('tourgames_file', models.ImageField(blank=True, default='default.png', upload_to='Tourgames')),
            ],
        ),
        migrations.CreateModel(
            name='TourMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourmovies_title', models.CharField(max_length=100)),
                ('tourmovies_video', models.FileField(default='', upload_to='Tourmovies/%y')),
                ('tourmovies_file', models.ImageField(blank=True, default='default.png', upload_to='Tourmovies')),
            ],
        ),
        migrations.CreateModel(
            name='TourMusics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourmusics_title', models.CharField(max_length=100)),
                ('tourmusics_video', models.FileField(default='', upload_to='Tourmusics/%y')),
                ('tourmusics_file', models.ImageField(blank=True, default='default.png', upload_to='Tourmusics')),
            ],
        ),
        migrations.CreateModel(
            name='TourNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournews_title', models.CharField(max_length=100)),
                ('tournews_video', models.FileField(default='', upload_to='Tournews/%y')),
                ('tournews_file', models.ImageField(blank=True, default='default.png', upload_to='Tournews')),
            ],
        ),
        migrations.CreateModel(
            name='TourSports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toursports_title', models.CharField(max_length=100)),
                ('toursports_video', models.FileField(default='', upload_to='Toursports/%y')),
                ('toursports_file', models.ImageField(blank=True, default='default.png', upload_to='Toursports')),
            ],
        ),
    ]
