# Generated by Django 3.1.1 on 2022-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0053_tourgames_tourmovies_tourmusics_tournews_toursports'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoinoniaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koinoniavid_title', models.CharField(max_length=100)),
                ('koinoniavid_video', models.FileField(default='', upload_to='Koinoniavid/%y')),
                ('koinoniavid_file', models.ImageField(blank=True, default='default.png', upload_to='Koinoniavid')),
            ],
        ),
    ]
