# Generated by Django 3.1.1 on 2022-01-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0054_koinoniavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoinoniaAMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koinoniaamo_title', models.CharField(max_length=100)),
                ('koinoniaamo_url', models.URLField()),
                ('koinoniaamo_file', models.ImageField(blank=True, default='default.png', upload_to='koinoniaamo_icons')),
            ],
        ),
        migrations.CreateModel(
            name='KoinoniaVidAMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koinoniavidamo_title', models.CharField(max_length=100)),
                ('koinoniavidamo_video', models.FileField(default='', upload_to='Koinoniavidamo/%y')),
                ('koinoniavidamo_file', models.ImageField(blank=True, default='default.png', upload_to='Koinoniavidamo')),
            ],
        ),
    ]
