# Generated by Django 3.1.1 on 2040-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0055_koinoniaamo_koinoniavidamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gospel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gospel_title', models.CharField(max_length=100)),
                ('gospel_video', models.FileField(default='', upload_to='Gospel/%y')),
                ('gospel_file', models.ImageField(blank=True, default='default.png', upload_to='Gospel')),
            ],
        ),
    ]
