# Generated by Django 3.1.1 on 2040-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaysite', '0056_gospel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_title', models.CharField(max_length=100)),
                ('crypto_url', models.URLField()),
                ('crypto_file', models.ImageField(blank=True, default='default.png', upload_to='crypto_icons')),
            ],
        ),
        migrations.CreateModel(
            name='ICT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ict_title', models.CharField(max_length=100)),
                ('ict_url', models.URLField()),
                ('ict_file', models.ImageField(blank=True, default='default.png', upload_to='ict_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_title', models.CharField(max_length=100)),
                ('wallet_url', models.URLField()),
                ('wallet_file', models.ImageField(blank=True, default='default.png', upload_to='wallet_icons')),
            ],
        ),
    ]
